name: deploy_frontend 
#deploys when push is  made from frontend folder
on:
    push:
        branches: [ main ]
        paths:
        - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_RESUME_SECRET }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.51.0
        inlineScript: |
            az storage blob upload-batch --account-name azureresumeaacg1 --auth-mode key -d '$web' -s frontend/ 
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:    
        azcliversion: 2.51.0
        inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name "SurajyadavResume" --name "SurajyadavResume" --resource-group "azure-resume-rg"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()